import {spawnSync} from 'node:child_process';
import {access,copyFile,mkdir,readFile,writeFile} from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';
import {makeBeats} from './beats.mjs';
import {researchTopic} from './research.mjs';
import {buildScript} from './script-engine.mjs';
import {planVisuals,promptsFor} from './visuals.mjs';
import {makeCaptions} from './captions.mjs';
import {validateAudioMix} from './audio.mjs';
import {digest,json,parseArgs,selectedStages,slugify,writeJson} from './utils.mjs';

const ROOT=process.cwd();
const exists=async(file)=>access(file).then(()=>true,()=>false);
function toneWav(seconds=40,{sampleRate=16000,frequency=180,volume=.12,pulsed=false}={}){const samples=Math.ceil(seconds*sampleRate),data=Buffer.alloc(samples*2),b=Buffer.alloc(44+data.length);for(let i=0;i<samples;i++){const envelope=pulsed?(i/sampleRate%2.6<.12?1:0):1;data.writeInt16LE(Math.round(Math.sin(2*Math.PI*frequency*i/sampleRate)*32767*volume*envelope),i*2);} b.write('RIFF');b.writeUInt32LE(36+data.length,4);b.write('WAVEfmt ',8);b.writeUInt32LE(16,16);b.writeUInt16LE(1,20);b.writeUInt16LE(1,22);b.writeUInt32LE(sampleRate,24);b.writeUInt32LE(sampleRate*2,28);b.writeUInt16LE(2,32);b.writeUInt16LE(16,34);b.write('data',36);b.writeUInt32LE(data.length,40);data.copy(b,44);return b;}
function placeholderSvg(beat,hero){const safe=(s)=>String(s).replace(/[&<>"']/g,(c)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c])); return `<svg xmlns="http://www.w3.org/2000/svg" width="1080" height="1920"><rect width="1080" height="1920" fill="#e8dcc0"/><path d="M70 80H1010V1640H70Z" fill="#f4ecd9" stroke="#1d2428" stroke-width="9" stroke-dasharray="22 12"/><text x="95" y="180" font-family="monospace" font-size="48" fill="#a92c22">${safe(beat.id)}</text><text x="95" y="780" font-family="sans-serif" font-size="58" font-weight="bold" fill="#1d2428">${safe(beat.coreIdea)}</text><text x="95" y="880" font-family="sans-serif" font-size="36" fill="#1d2428">HERO: ${safe(hero)}</text><rect x="72" y="1510" width="936" height="250" fill="none" stroke="#d39b32" stroke-width="10"/><text x="95" y="1700" font-family="monospace" font-size="30">CAPTION SAFE AREA - PLACEHOLDER ONLY</text></svg>`;}
// Factory rules prohibit conventional verbatim subtitles. These are short,
// editorial scene headlines derived from the beat's visual idea.
const ffprobePath=()=>process.env.FFPROBE_PATH||path.join(ROOT,'node_modules','@remotion','compositor-linux-x64-gnu','ffprobe');
function inspectVideo(file){const result=spawnSync(ffprobePath(),['-v','error','-show_entries','format=duration,size:stream=index,codec_type,codec_name,width,height,r_frame_rate','-of','json',file],{encoding:'utf8'});if(result.status!==0)throw new Error(`FFprobe başarısız: ${result.stderr}`);const data=JSON.parse(result.stdout),video=data.streams.find((s)=>s.codec_type==='video'),audio=data.streams.find((s)=>s.codec_type==='audio');return {file,sizeBytes:Number(data.format.size),width:video.width,height:video.height,fps:video.r_frame_rate,durationSeconds:Number(data.format.duration),videoCodec:video.codec_name,audioCodec:audio?.codec_name||null,videoStreams:data.streams.filter((s)=>s.codec_type==='video').length,audioStreams:data.streams.filter((s)=>s.codec_type==='audio').length};}

export async function runVox(argv){
 const started=Date.now(); const options=parseArgs(argv); let project=options.project?path.resolve(ROOT,options.project):path.join(ROOT,'output',slugify(options.topic)); await mkdir(project,{recursive:true});
 for(const directory of ['images','layers','clips','audio','thumbnail']) await mkdir(path.join(project,directory),{recursive:true});
 const previousInput=await exists(path.join(project,'input.json'))?await json(path.join(project,'input.json')):null; const topic=options.topic||previousInput?.topic; if(!topic)throw new Error('--project devamında input.json veya --topic gerekir.');
 const input={projectId:path.basename(project),topic,duration:options.duration,language:options.language,seed:options.seed,autoUpload:false,requireManualApproval:true,allowPaidGeneration:false,enableAiVideo:false,createdBy:'vox-documentary-engine'}; await writeJson(path.join(project,'input.json'),input);
 const manifestPath=path.join(project,'.vox-manifest.json'); const manifest=await exists(manifestPath)?await json(manifestPath):{version:1,stages:{}}; const report={projectId:input.projectId,startedAt:new Date().toISOString(),dryRun:options.dryRun,uploadEnabled:false,warnings:[],changes:[],stages:{}};
 const wanted=selectedStages(options); const run=async(name,fingerprint,fn)=>{const hash=digest(fingerprint); if(!options.force&&options.resume&&manifest.stages[name]?.hash===hash&&await exists(path.join(project,manifest.stages[name].artifact))){report.stages[name]='cached';return;} const artifact=await fn(); manifest.stages[name]={hash,artifact,completedAt:new Date().toISOString()};report.stages[name]='completed';await writeJson(manifestPath,manifest);};
 if(wanted.includes('research'))await run('research',input,async()=>{await writeJson(path.join(project,'research.json'),researchTopic(topic));return 'research.json';});
 const research=await json(path.join(project,'research.json')); if(research.warning)report.warnings.push(research.warning);
 if(wanted.includes('script'))await run('script',{input,research},async()=>{await writeJson(path.join(project,'script.json'),buildScript({...input,research}));return 'script.json';});
 const script=await json(path.join(project,'script.json'));
 if(wanted.includes('voice'))await run('voice',{script,duration:input.duration},async()=>{await mkdir(path.join(project,'audio'),{recursive:true});await writeFile(path.join(project,'audio','voice.wav'),toneWav(input.duration,{frequency:165,volume:.08}));await writeJson(path.join(project,'audio','voice-metadata.json'),{provider:'deterministic-local-fixture',voiceMode:'fixture',alignmentMode:'estimated',durationSeconds:input.duration,productionReady:false,warning:'Konuşma TTS sağlayıcısı bulunmadı; deterministik ses fixture kullanıldı.'});report.warnings.push('Geliştirme ses fixture production için uygun değildir.');return 'audio/voice.wav';});
 if(wanted.includes('beats'))await run('beats',{script,duration:input.duration},async()=>{await writeJson(path.join(project,'beats.json'),makeBeats(script,input.duration));return 'beats.json';});
 const beats=await json(path.join(project,'beats.json'));
 const style=await json(path.join(ROOT,'config','vox-style.json'));
 if(wanted.includes('visuals'))await run('visuals',{beats,research,style},async()=>{const plan=planVisuals(beats,research);await writeJson(path.join(project,'visual-plan.json'),plan);await writeFile(path.join(project,'image-prompts.txt'),`${promptsFor(plan,style)}\n`);return 'visual-plan.json';});
 const visual=await json(path.join(project,'visual-plan.json'));
 if(wanted.includes('images'))await run('images',{visual,seed:input.seed,provider:options.provider||'placeholder'},async()=>{await mkdir(path.join(project,'images'),{recursive:true});for(const beat of beats.beats){const v=visual.beats.find((x)=>x.beatId===beat.id);await writeFile(path.join(project,'images',`${beat.id}.svg`),placeholderSvg(beat,v.heroElement));}await writeJson(path.join(project,'images','metadata.json'),{provider:'local-placeholder',productionReady:false,count:beats.beats.length,retries:0});report.warnings.push('Placeholder görseller production çıktısı değildir.');return 'images/metadata.json';});
 if(wanted.includes('captions'))await run('captions',{beats,safe:style.captionSafeArea},async()=>{const value={safeArea:style.captionSafeArea,maxRenderedLineCount:2,overflow:false,captions:makeCaptions(beats,style.captionSafeArea)};await writeJson(path.join(project,'captions.json'),value);return 'captions.json';});
 if(wanted.includes('audio'))await run('audio',{voice:manifest.stages.voice?.hash,seed:input.seed},async()=>{await writeFile(path.join(project,'audio','music.wav'),toneWav(input.duration,{frequency:82,volume:.025}));await writeFile(path.join(project,'audio','paper-sfx.wav'),toneWav(.25,{frequency:420,volume:.15,pulsed:true}));await writeFile(path.join(project,'audio','event-sfx.wav'),toneWav(.4,{frequency:110,volume:.18}));await writeFile(path.join(project,'audio','ambience.wav'),toneWav(input.duration,{frequency:55,volume:.012}));await writeJson(path.join(project,'audio','mix.json'),{voice:{path:'audio/voice.wav',volume:1},music:{path:'audio/music.wav',volume:.12,duckedVolume:.045},paperSfx:[{path:'audio/paper-sfx.wav',frame:0,volume:.2}],eventSfx:[{path:'audio/event-sfx.wav',frame:600,volume:.24}],ambience:{path:'audio/ambience.wav',volume:.08},ducking:true,mood:'historical_tension',musicIntensity:.35,sfxProfile:'paper_mechanical'});return 'audio/mix.json';});
 const captionData=await json(path.join(project,'captions.json')); const publicDir=path.join(ROOT,'public','generated','vox-current');
 const mix=await json(path.join(project,'audio','mix.json'));await validateAudioMix(project,mix);const pubAudio=(name)=>`generated/vox-current/audio/${name}`;const videoData={projectId:input.projectId,width:1080,height:1920,fps:30,durationInFrames:Math.round(beats.durationSeconds*30),voiceover:pubAudio('voice.wav'),music:{src:pubAudio('music.wav'),volume:mix.music.volume,duckedVolume:mix.music.duckedVolume},paperSfx:mix.paperSfx.map((x)=>({...x,src:pubAudio(path.basename(x.path))})),eventSfx:mix.eventSfx.map((x)=>({...x,src:pubAudio(path.basename(x.path))})),ambience:{src:pubAudio('ambience.wav'),volume:mix.ambience.volume},captions:captionData.captions,sceneHeadlines:[],beats:beats.beats.map((b)=>{const v=visual.beats.find((x)=>x.beatId===b.id);return {...b,sceneType:'still_collage',image:`generated/vox-current/images/${b.id}.svg`,motionPreset:v.motionPreset,transitionPreset:v.transitionPreset,editorialLabel:v.label};})}; await writeJson(path.join(project,'video-data.json'),videoData);
 if(wanted.includes('render')){if(options.dryRun){report.stages.render='skipped-dry-run';}else{await mkdir(path.join(publicDir,'images'),{recursive:true});await mkdir(path.join(publicDir,'audio'),{recursive:true});for(const b of beats.beats)await copyFile(path.join(project,'images',`${b.id}.svg`),path.join(publicDir,'images',`${b.id}.svg`));for(const name of ['voice.wav','music.wav','paper-sfx.wav','event-sfx.wav','ambience.wav'])await copyFile(path.join(project,'audio',name),path.join(publicDir,'audio',name));const props=path.join(project,'remotion-props.json');await writeJson(props,{videoData});const result=spawnSync('npx',['remotion','render','src/index.ts','VoxShort',path.join(project,'final.mp4'),'--props',props,'--codec=h264','--pixel-format=yuv420p'],{cwd:ROOT,stdio:'inherit'});if(result.status!==0)throw new Error(`Remotion render başarısız: ${result.status}`);report.stages.render='completed';}}
 let probe=null;if(wanted.includes('qc')){const rendered=await exists(path.join(project,'final.mp4'));probe=rendered?inspectVideo(path.join(project,'final.mp4')):null;const technicalPassed=Boolean(probe&&probe.width===1080&&probe.height===1920&&probe.fps==='30/1'&&probe.videoCodec==='h264'&&probe.audioStreams>0);const qc={technical:{status:technicalPassed?'passed':'failed',checks:probe?[probe]:[{rendered:false}]},editorial:{status:'manual_review',checks:[{criticalClaimsVerified:research.verifiedFacts.length>0},{emDashFree:!script.script.includes('—')},{captionOverflow:false,maxRenderedLineCount:captionData.maxRenderedLineCount}]},publication:{status:'blocked',reasons:['placeholder visual assets','development or fallback audio','manual approval pending']}};await writeJson(path.join(project,'qc-report.json'),qc);report.stages.qc='completed';}
 const motionPresetsUsed=[...new Set(videoData.beats.map((x)=>x.motionPreset))],transitionsUsed=[...new Set(videoData.beats.map((x)=>x.transitionPreset))];Object.assign(report,{seed:input.seed,completedAt:new Date().toISOString(),durationMs:Date.now()-started,providers:{research:'verified-fixture',voice:'deterministic-local-fixture',image:'local-placeholder'},voiceMode:'fixture',alignmentMode:'estimated',imageMode:'placeholder',placeholderCount:beats.beats.length,motionPresetsUsed,transitionsUsed,uniqueMotionPresetCount:motionPresetsUsed.length,uniqueTransitionCount:transitionsUsed.length,estimatedCost:0,currency:'TRY',paidGenerationAllowed:false,uploadAttempted:false,autoUpload:false,requireManualApproval:true,enableAiVideo:false,ffprobe:probe});await writeJson(path.join(project,'production-report.json'),report);console.log(JSON.stringify({project,stages:report.stages,motionPresetsUsed,transitionsUsed,warnings:report.warnings,uploadEnabled:false},null,2));return {project,report};
}
