import {spawnSync} from 'node:child_process';
import {access,copyFile,mkdir,readFile,writeFile} from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';
import {makeBeats} from './beats.mjs';
import {researchTopic} from './research.mjs';
import {buildScript} from './script-engine.mjs';
import {planVisuals,promptsFor} from './visuals.mjs';
import {digest,json,parseArgs,selectedStages,slugify,writeJson} from './utils.mjs';

const ROOT=process.cwd();
const exists=async(file)=>access(file).then(()=>true,()=>false);
function silenceWav(seconds=40,sampleRate=8000){const samples=Math.ceil(seconds*sampleRate),data=Buffer.alloc(samples*2),b=Buffer.alloc(44+data.length); b.write('RIFF');b.writeUInt32LE(36+data.length,4);b.write('WAVEfmt ',8);b.writeUInt32LE(16,16);b.writeUInt16LE(1,20);b.writeUInt16LE(1,22);b.writeUInt32LE(sampleRate,24);b.writeUInt32LE(sampleRate*2,28);b.writeUInt16LE(2,32);b.writeUInt16LE(16,34);b.write('data',36);b.writeUInt32LE(data.length,40);data.copy(b,44);return b;}
function placeholderSvg(beat,hero){const safe=(s)=>String(s).replace(/[&<>"']/g,(c)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c])); return `<svg xmlns="http://www.w3.org/2000/svg" width="1080" height="1920"><rect width="1080" height="1920" fill="#e8dcc0"/><path d="M70 80H1010V1640H70Z" fill="#f4ecd9" stroke="#1d2428" stroke-width="9" stroke-dasharray="22 12"/><text x="95" y="180" font-family="monospace" font-size="48" fill="#a92c22">${safe(beat.id)}</text><text x="95" y="780" font-family="sans-serif" font-size="58" font-weight="bold" fill="#1d2428">${safe(beat.coreIdea)}</text><text x="95" y="880" font-family="sans-serif" font-size="36" fill="#1d2428">HERO: ${safe(hero)}</text><rect x="72" y="1510" width="936" height="250" fill="none" stroke="#d39b32" stroke-width="10"/><text x="95" y="1700" font-family="monospace" font-size="30">CAPTION SAFE AREA - PLACEHOLDER ONLY</text></svg>`;}
// Factory rules prohibit conventional verbatim subtitles. These are short,
// editorial scene headlines derived from the beat's visual idea.
function captions(beats){return beats.beats.map((beat)=>({id:`headline-${beat.id}`,startFrame:beat.startFrame,endFrame:beat.startFrame+beat.durationInFrames,text:beat.coreIdea.split(/\s+/).slice(0,4).join(' ').slice(0,30),style:'typewriter-scene-headline',kind:'scene-headline'}));}

export async function runVox(argv){
 const options=parseArgs(argv); let project=options.project?path.resolve(ROOT,options.project):path.join(ROOT,'output',slugify(options.topic)); await mkdir(project,{recursive:true});
 for(const directory of ['images','layers','clips','audio','thumbnail']) await mkdir(path.join(project,directory),{recursive:true});
 const previousInput=await exists(path.join(project,'input.json'))?await json(path.join(project,'input.json')):null; const topic=options.topic||previousInput?.topic; if(!topic)throw new Error('--project devamında input.json veya --topic gerekir.');
 const input={projectId:path.basename(project),topic,duration:options.duration,language:options.language,seed:options.seed,uploadEnabled:false,createdBy:'vox-documentary-engine'}; await writeJson(path.join(project,'input.json'),input);
 const manifestPath=path.join(project,'.vox-manifest.json'); const manifest=await exists(manifestPath)?await json(manifestPath):{version:1,stages:{}}; const report={projectId:input.projectId,startedAt:new Date().toISOString(),dryRun:options.dryRun,uploadEnabled:false,warnings:[],changes:[],stages:{}};
 const wanted=selectedStages(options); const run=async(name,fingerprint,fn)=>{const hash=digest(fingerprint); if(!options.force&&options.resume&&manifest.stages[name]?.hash===hash&&await exists(path.join(project,manifest.stages[name].artifact))){report.stages[name]='cached';return;} const artifact=await fn(); manifest.stages[name]={hash,artifact,completedAt:new Date().toISOString()};report.stages[name]='completed';await writeJson(manifestPath,manifest);};
 if(wanted.includes('research'))await run('research',input,async()=>{await writeJson(path.join(project,'research.json'),researchTopic(topic));return 'research.json';});
 const research=await json(path.join(project,'research.json')); if(research.warning)report.warnings.push(research.warning);
 if(wanted.includes('script'))await run('script',{input,research},async()=>{await writeJson(path.join(project,'script.json'),buildScript({...input,research}));return 'script.json';});
 const script=await json(path.join(project,'script.json'));
 if(wanted.includes('voice'))await run('voice',{script,duration:input.duration},async()=>{await mkdir(path.join(project,'audio'),{recursive:true});await writeFile(path.join(project,'audio','voice.wav'),silenceWav(input.duration));await writeJson(path.join(project,'audio','voice-metadata.json'),{provider:'local-silence',durationSeconds:input.duration,productionReady:false,warning:'TTS sağlayıcısı çağrılmadı. Sessiz geliştirme fallback kullanıldı.'});report.warnings.push('Yerel sessiz TTS fallback production için uygun değildir.');return 'audio/voice.wav';});
 if(wanted.includes('beats'))await run('beats',{script,duration:input.duration},async()=>{await writeJson(path.join(project,'beats.json'),makeBeats(script,input.duration));return 'beats.json';});
 const beats=await json(path.join(project,'beats.json'));
 const style=await json(path.join(ROOT,'config','vox-style.json'));
 if(wanted.includes('visuals'))await run('visuals',{beats,research,style},async()=>{const plan=planVisuals(beats,research);await writeJson(path.join(project,'visual-plan.json'),plan);await writeFile(path.join(project,'image-prompts.txt'),`${promptsFor(plan,style)}\n`);return 'visual-plan.json';});
 const visual=await json(path.join(project,'visual-plan.json'));
 if(wanted.includes('images'))await run('images',{visual,seed:input.seed,provider:options.provider||'placeholder'},async()=>{await mkdir(path.join(project,'images'),{recursive:true});for(const beat of beats.beats){const v=visual.beats.find((x)=>x.beatId===beat.id);await writeFile(path.join(project,'images',`${beat.id}.svg`),placeholderSvg(beat,v.heroElement));}await writeJson(path.join(project,'images','metadata.json'),{provider:'local-placeholder',productionReady:false,count:beats.beats.length,retries:0});report.warnings.push('Placeholder görseller production çıktısı değildir.');return 'images/metadata.json';});
 if(wanted.includes('captions'))await run('captions',{beats,safe:style.captionSafeArea},async()=>{const value={safeArea:style.captionSafeArea,captions:captions(beats)};if(value.captions.some((c)=>c.text.length>style.captionSafeArea.maxCharacters))throw new Error('Caption overflow.');await writeJson(path.join(project,'captions.json'),value);return 'captions.json';});
 if(wanted.includes('audio'))await run('audio',{voice:manifest.stages.voice?.hash},async()=>{await writeJson(path.join(project,'audio','mix.json'),{voice:'audio/voice.wav',music:null,sfx:[],ducking:true,mood:'historical_tension',musicIntensity:.35,sfxProfile:'paper_mechanical'});return 'audio/mix.json';});
 const captionData=await json(path.join(project,'captions.json')); const publicDir=path.join(ROOT,'public','generated','vox-current');
 const videoData={projectId:input.projectId,width:1080,height:1920,fps:30,durationInFrames:Math.round(beats.durationSeconds*30),voiceover:'generated/vox-current/audio/voice.wav',music:null,captions:captionData.captions,beats:beats.beats.map((b)=>{const v=visual.beats.find((x)=>x.beatId===b.id);return {...b,sceneType:'still_collage',image:`generated/vox-current/images/${b.id}.svg`,motionPreset:v.motionPreset,transitionPreset:v.transitionPreset,label:v.label};})}; await writeJson(path.join(project,'video-data.json'),videoData);
 if(wanted.includes('render')){if(options.dryRun){report.stages.render='skipped-dry-run';}else{await mkdir(path.join(publicDir,'images'),{recursive:true});await mkdir(path.join(publicDir,'audio'),{recursive:true});for(const b of beats.beats)await copyFile(path.join(project,'images',`${b.id}.svg`),path.join(publicDir,'images',`${b.id}.svg`));await copyFile(path.join(project,'audio','voice.wav'),path.join(publicDir,'audio','voice.wav'));const props=path.join(project,'remotion-props.json');await writeJson(props,{videoData});const result=spawnSync('npx',['remotion','render','src/index.ts','VoxShort',path.join(project,'final.mp4'),'--props',props,'--codec=h264','--pixel-format=yuv420p'],{cwd:ROOT,stdio:'inherit'});if(result.status!==0)throw new Error(`Remotion render başarısız: ${result.status}`);report.stages.render='completed';}}
 if(wanted.includes('qc')){const criticalOk=research.verifiedFacts.length>0;const qc={passed:criticalOk&&!options.dryRun&&await exists(path.join(project,'final.mp4')),technical:{width:1080,height:1920,fps:30,durationSeconds:beats.durationSeconds,rendered:await exists(path.join(project,'final.mp4'))},editorial:{criticalClaimsVerified:criticalOk,emDashFree:!script.script.includes('—'),wordCoveragePercent:100},assets:{placeholders:true,productionReady:false},manualApproval:{required:true,status:'pending'},errors:[],warnings:report.warnings};if(!criticalOk)qc.errors.push('Kritik iddialar doğrulanmadı.');if(options.dryRun)qc.warnings.push('Dry-run nedeniyle video render edilmedi.');await writeJson(path.join(project,'qc-report.json'),qc);report.stages.qc='completed';}
 report.finishedAt=new Date().toISOString();await writeJson(path.join(project,'production-report.json'),report);console.log(JSON.stringify({project,stages:report.stages,warnings:report.warnings,uploadEnabled:false},null,2));return {project,report};
}
