import React from 'react';
import {AbsoluteFill,Audio,Img,Sequence,staticFile,useCurrentFrame} from 'remotion';
import {motionStyle} from './motion';
import type {VoxVideoData} from './types';

export const sampleVideoData:VoxVideoData={projectId:'vox-preview',width:1080,height:1920,fps:30,durationInFrames:1200,voiceover:'audio/voice.mp3',music:null,captions:[],beats:[]};
const BeatScene:React.FC<{beat:VoxVideoData['beats'][number]}> = ({beat})=>{const frame=useCurrentFrame();return <AbsoluteFill style={{background:'#182126',overflow:'hidden'}}><div style={{position:'absolute',inset:24,background:'#eadfc7',filter:'drop-shadow(0 18px 20px #0008)',...motionStyle(beat.motionPreset,frame,beat.durationInFrames)}}><Img src={staticFile(beat.image)} style={{width:'100%',height:'100%',objectFit:'cover'}}/></div>{beat.label?<div style={{position:'absolute',left:72,top:100,padding:'12px 20px',background:'#d29a32',font:'700 42px monospace'}}>{beat.label}</div>:null}</AbsoluteFill>};
const CaptionStrip:React.FC<{cue:VoxVideoData['captions'][number]}> = ({cue})=><Sequence from={cue.startFrame} durationInFrames={Math.max(1,cue.endFrame-cue.startFrame)}><div style={{position:'absolute',zIndex:20,left:72,right:72,bottom:300,textAlign:'center'}}><span style={{display:'inline-block',padding:'14px 20px',background:'#f5ecd8',color:'#182126',font:'700 42px monospace',lineHeight:1.15,boxShadow:'8px 10px 0 #0004',textTransform:'uppercase'}}>{cue.text}</span></div></Sequence>;
export const VoxShort:React.FC<{videoData?:VoxVideoData}>=({videoData=sampleVideoData})=><AbsoluteFill style={{background:'#182126'}}>{videoData.beats.map((beat)=><Sequence key={beat.id} from={beat.startFrame} durationInFrames={beat.durationInFrames}><BeatScene beat={beat}/></Sequence>)}{videoData.captions.map((cue)=><CaptionStrip key={cue.id} cue={cue}/>)}{videoData.voiceover?<Audio src={staticFile(videoData.voiceover)}/>:null}{videoData.music?<Audio src={staticFile(videoData.music)} volume={.12}/>:null}</AbsoluteFill>;
