import {readFile, writeFile, access} from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';

export const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');

/**
 * WHERE AN EPISODE LIVES.
 *
 * Normally `episodes/<id>`, and an id is a name — never a path. A hand-written
 * `--episode=../secrets` would otherwise resolve wherever it liked, and every
 * script here reads and WRITES inside whatever comes back.
 *
 * `EPISODES_DIR` moves the whole shelf somewhere else, which is what lets the
 * robustness tests plan hostile briefs in a temp directory instead of dropping
 * scratch folders into the repo for the other tests to trip over.
 */
export function episodeDir(episodeId) {
  const id = String(episodeId ?? '');
  if (!/^[A-Za-z0-9][A-Za-z0-9._-]*$/.test(id)) {
    throw new Error(`"${id}" is not an episode id — a name, not a path`);
  }
  return path.join(process.env.EPISODES_DIR || path.join(ROOT, 'episodes'), id);
}

/** `--episode=id` or `--episode id`. */
export function parseArgs(argv = process.argv.slice(2)) {
  const args = {};
  for (let i = 0; i < argv.length; i += 1) {
    const token = argv[i];
    if (!token.startsWith('--')) continue;
    const [key, inline] = token.slice(2).split('=');
    args[key] = inline ?? (argv[i + 1] && !argv[i + 1].startsWith('--') ? argv[(i += 1)] : true);
  }
  return args;
}

export async function loadConfig(episodeId) {
  const file = path.join(episodeDir(episodeId), 'scene-config.json');
  let raw;
  try {
    raw = await readFile(file, 'utf8');
  } catch {
    throw new Error(`scene-config.json not found for episode "${episodeId}" (looked in ${file})`);
  }
  try {
    return {config: JSON.parse(raw), file};
  } catch (error) {
    throw new Error(`scene-config.json is not valid JSON: ${error.message}`);
  }
}

export const exists = (file) => access(file).then(() => true).catch(() => false);

/**
 * Strip `?` from optional roles, dropping the ones whose file is not on disk.
 *
 * MUST run before any bundle. Remotion pre-loads every image it is handed, and
 * a 404 does not degrade to a blank layer — it raises an EncodingError that
 * cancels the whole render. So an absent optional asset that reaches the
 * browser is fatal, not cosmetic.
 *
 * It lives here rather than in the render script because it is needed by every
 * entry point that bundles — render, stills, previews. Putting it in one of
 * them is how you get a feature that works down a single path and 404s down all
 * the others.
 *
 * The validator deliberately does NOT use this: it reports absent optionals
 * rather than quietly removing them.
 */
export async function pruneOptionalAssets(config, episodeId) {
  const dir = episodeDir(episodeId);
  const dropped = [];
  for (const scene of config.scenes ?? []) {
    for (const [role, file] of Object.entries(scene.assets ?? {})) {
      if (!role.startsWith('?')) continue;
      delete scene.assets[role];
      if (typeof file === 'string' && (await exists(path.join(dir, file)))) {
        scene.assets[role.slice(1)] = file;
      } else {
        dropped.push(`${scene.id}.${role.slice(1)}`);
      }
    }
    // A layer pointing at a role that is no longer there would render nothing
    // and, worse, still take its turn in the stacking order.
    if (Array.isArray(scene.layers)) {
      scene.layers = scene.layers.filter((layer) => !layer.role || scene.assets?.[layer.role]);
    }
  }
  return dropped;
}

/**
 * Writes the generated override module the registry imports.
 *
 * An episode may ship `scenes/index.tsx` exporting extra scene templates. The
 * bundler needs a STATIC import to find them, so the path is written into a
 * generated file just before bundling rather than resolved at runtime — a
 * dynamic import here is exactly the kind of thing that works locally and
 * fails inside a CI bundle.
 */
const GENERATED = () => path.join(ROOT, 'engine', 'episodeScenes.generated.ts');

const HEADER =
  '// GENERATED by scripts/render-episode.mjs — do not edit.\n' +
  "import type React from 'react';\n" +
  "import type {SceneProps} from './sceneTypes/types';\n\n";

const EMPTY = `${HEADER}export const EPISODE_SCENE_OVERRIDES: Record<string, React.FC<SceneProps>> = {};\n`;

/**
 * Makes sure the generated module EXISTS, without choosing an episode.
 *
 * The file is git-ignored and normally written just before a bundle, so a fresh
 * checkout does not have one — and `tsc` fails on the import before anything
 * has been rendered. That is invisible locally, where a previous render has
 * always left one lying around, and fails in CI every time. Run before
 * typecheck and studio; it never overwrites a real one.
 */
export async function ensureSceneOverrides() {
  const generated = GENERATED();
  if (await exists(generated)) return false;
  await writeFile(generated, EMPTY, 'utf8');
  return true;
}

export async function writeSceneOverrides(episodeId) {
  const generated = GENERATED();
  const overrideEntry = path.join(episodeDir(episodeId), 'scenes', 'index.tsx');
  const header = HEADER;

  if (await exists(overrideEntry)) {
    const relative = path
      .relative(path.join(ROOT, 'engine'), overrideEntry)
      .split(path.sep)
      .join('/')
      .replace(/\.tsx$/, '');
    await writeFile(
      generated,
      `${header}import overrides from '${relative}';\n\n` +
        'export const EPISODE_SCENE_OVERRIDES: Record<string, React.FC<SceneProps>> = overrides;\n',
      'utf8',
    );
    return overrideEntry;
  }

  await writeFile(generated, EMPTY, 'utf8');
  return null;
}
